import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { FC, Props, useEffect, useLayoutEffect, useState } from 'react'
import { useSubscribe } from '../hooks/useSubscribe'
import styles from '../styles/Home.module.css'
import Confetti from 'react-confetti'
import { useInServer } from '../hooks/useInServer'
import mainLogo from '../public/anglerLOGO_03.svg'
import mainLogoText from '../public/main-logo-side-text-new.svg'
import {
  useWindowSize,
  useWindowWidth,
  useWindowHeight,
} from '@react-hook/window-size'


const HomePage:FC = () => {
  const {inServer} = useInServer()
  const [width, height] = useWindowSize()
  const {email , setemail , loading, subscribe, error , subscribeEmail ,  setloading , closeCongrat} = useSubscribe()
  const randomNumberBetween0and100 = Math.floor(Math.random() * 100)
  const randomNumber2Between0and100 = Math.floor(Math.random() * 100)
  const [initialWidth, setinitialWidth] = useState(0)
  const [initialHeight, setinitialHeight] = useState(0)
  
  useLayoutEffect(() => {
    setinitialWidth(width)
    setinitialHeight(height)
  }, [])


  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    subscribeEmail(email)
  }
 
  useEffect(() => {
    if(!inServer){
      document.getElementById('easterBtn')?.setAttribute('style', `top:${randomNumberBetween0and100}px;left:${randomNumber2Between0and100}px;`)
    }
  }, [inServer])

  if(inServer)return <></>
  return (
    <div className={styles.container}>
      <Head>
        <title>ABYSS Cooming Soon </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        loading === 'failed' && 
        <>
        <div className={styles.succesCont}>
          <Confetti width={window.innerWidth}/>
          <div className={styles.succesModal}>
            <button className={styles.closeBtn} onClick={closeCongrat}>❌</button>
            <h1>🎉 {email}</h1>
            <p>you will notified when platform released</p>  
          </div>
        </div>
        </>
      }


      <main className={styles.main}>
        <div className={styles.toptitle}> 
          {/* <div className={styles.easterTip}>{randomNumberBetween0and100}px  x {randomNumber2Between0and100}px </div> */}
          
          <Image src={mainLogo} width={(height * 0.382 * 0.382 * 0.764) * 1.0618} height={height * 0.382 * 0.382 * 0.764}  alt="Abyss Logo"/> 
          <div style={{height:`${height * Math.pow(0.236 , 3)}px`}}></div>
          <Image src={mainLogoText} alt="Abyss Logo" width={(height * 0.382 * 0.382 * 0.472) * 2.5} height={height * 0.382 * 0.382 * 0.472}/> 
        </div>

        <button className={styles.easterBtn} id={'easterBtn'}> </button>
        
        <div className={styles.videoBlock}>
          {/* 0.236 , 2 */}
            <div style={{height:`${window.innerHeight * Math.pow( 0.236, 2) * 0.618}px`}}></div>
            <h2 className={styles.titleh2}>Your hub for first-hand <span> solutions </span></h2>

            <p className={styles.subtitle}>A tool for developers, a blessing for creators</p>
            <div style={{height:`${window.innerHeight * Math.pow( 0.236, 2) * 0.618}px`}}></div>

            <iframe  className={styles.video} width={initialWidth * 0.5}  height={(initialWidth * 0.5) * (9 / 16)} src="https://www.youtube.com/embed/vtfOsFd99r8" title="YouTube video player"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe>
            <form onSubmit={handleSubmit} action="">
              <div className={styles.inputBox}>
                <input disabled={loading === 'pending'} value={email} onChange={(e:any) => setemail(e.target.value)} type="email"  placeholder='Email address'/>
                <button disabled={loading === 'pending'}>Send Email</button>
              </div>
              <span className={styles.error}>{error}</span>
            </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          <p>Powered by</p>
          <span className={styles.logo}>
            <Image src={mainLogo}  alt="Abyss Logo" width={30} height={20} />
            <Image src={mainLogoText} alt="Abyss Logo" width={50} height={30} />
          </span>
        </a>
      </footer>

      
    </div>
  )
}

export default HomePage
